version: '3.3'

services:
  mba-svelte:
    build: .
    env_file: .env
    volumes:
      - '.data:/usr/app/.data'
#    ports: # Add this when not running with Caddy
#      - '127.0.0.1:26799:26799' 
    restart: 'unless-stopped'

# Optional caddy configuration. Also see Caddyfile
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
